package com.davidmoreno.jetpackdemo.util

val DELAY: Long = 5000

//Fragments identifiers
val LOGIN_RECOVERY_FRAGMENT_TAG = "LOGIN_RECOVERY_FRAGMENT_TAG"
val LOGIN_FRAGMENT_TAG = "LOGIN_FRAGMENT_TAG"
val LOADING_FRAGMENT_TAG = "LOADING_FRAGMENT"